# suppress inspection "UnusedProperty" for whole file

ideaVersion=2021.3
downloadIdeaSources=true
instrumentPluginCode=true
version=1.10.0
javaVersion=11
remoteRobotVersion=0.11.10

# Please don't forget to update kotlin version in buildscript section
kotlinVersion=1.5.10
publishToken=token
publishChannels=eap

slackUrl=

# Gradle settings
org.gradle.jvmargs='-Dfile.encoding=UTF-8'

# Proxy
systemProp.http.proxyHost=127.0.0.1
systemProp.http.proxyPort=7890
systemProp.https.proxyHost=127.0.0.1
systemProp.https.proxyPort=7890